# Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
    - python

python:
    - "3.3"

env:
    - TOOLCHAIN=clang_libstdcxx TYPE=Debug
    - TOOLCHAIN=clang_libstdcxx TYPE=Release
    - TOOLCHAIN=gcc48 TYPE=Debug
    - TOOLCHAIN=gcc48 TYPE=Release

install:
    # install gcc-4.8 with c++11 support: https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install g++-4.8
    # -- end
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # install cmake
    - CMAKE_VERSION="3.2.1-ruslo"
    - wget https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz
    - openssl sha1 v${CMAKE_VERSION}.tar.gz
    - tar xf v${CMAKE_VERSION}.tar.gz
    - cmake -HCMake-${CMAKE_VERSION} -B_builds-cmake -DCMAKE_USE_SYSTEM_CURL=YES -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="`pwd`/_install"
    - cmake --build _builds-cmake --target install
    - export PATH="`pwd`/_install/bin:${PATH}"
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end
    # install cmake toolchains
    - POLLY_VERSION="0.3.1"
    - wget https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz
    - tar xf v${POLLY_VERSION}.tar.gz
    - export POLLY_ROOT=`pwd`/polly-${POLLY_VERSION}
    # -- end

script:
    - chmod +x run-test.py
    - ./run-test.py --toolchain ${TOOLCHAIN} --type ${TYPE}
