language:
    - cpp

env:
    - TOOLCHAIN=default
    - TOOLCHAIN=clang_libstdcxx
    - TOOLCHAIN=gcc48

install:
    - sudo apt-get upgrade
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # install cmake
    - CMAKE_VERSION="3.0.0-ios-universal"
    - wget https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz
    - openssl sha1 v${CMAKE_VERSION}.tar.gz
    - tar xf v${CMAKE_VERSION}.tar.gz
    - cmake -HCMake-${CMAKE_VERSION} -B_builds-cmake -DCMAKE_USE_SYSTEM_CURL=YES -DCMAKE_BUILD_TYPE=Release
    - cmake --build _builds-cmake
    - sudo cmake --build _builds-cmake --target install
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end
    # install cmake toolchains
    - POLLY_VERSION="0.3.1"
    - wget https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz
    - tar xf v${POLLY_VERSION}.tar.gz
    - export POLLY_ROOT=`pwd`/polly-${POLLY_VERSION}
    # -- end

script:
    - export TOOLCHAIN_FILE="${POLLY_ROOT}/${TOOLCHAIN}.cmake"
    - chmod +x run-test.sh
    - ./run-test.sh
